- name: set login to tacacs if tacacs is defined
  set_fact: ansible_ssh_user={{ fanout_tacacs_eos_user }} ansible_ssh_password={{ fanout_tacacs_eos_password }}
  when: >
    fanout_tacacs_user is not defined and fanout_tacacs_user is not defined and
    fanout_tacacs_eos_user is defined and fanout_tacacs_eos_password is defined

- name: prepare fanout switch admin login info
  set_fact: ansible_ssh_user={{ fanout_admin_user }} ansible_ssh_password={{ fanout_admin_password }}
  when: >
    fanout_tacacs_user is not defined and fanout_tacacs_user is not defined and
    fanout_tacacs_eos_user is not defined and fanout_tacacs_eos_password is not defined

- name: create persistent shell login
  file: path=/mnt/flash/rc.eos state=touch
  become: yes

- name: save persistent shell login
  template: src=rc.eos.j2
            dest=/mnt/flash/rc.eos
  become: yes

- name: build fanout startup config for Arista fanout leaf
  template: src=arista_7260_deploy.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "Arista-7260QX-64"
  become: yes

- name: build fanout startup config for 7060
  template: src=arista_7060_deploy.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "Arista-7060CX-32S"
  become: yes

- name: build fanout startup config for 7260cx3
  template: src=arista_7260cx3_deploy.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "Arista-7260CX3"
  become: yes

- name: build fanout startup config for 7060dx4
  template: src=arista_7060_deploy.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "Arista-7060DX4-32"
  become: yes

- name: build fanout startup config for Seastone_2
  template: src=Seastone_2.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "Seastone_2"
  become: yes

- name: build fanout startup config for SSE-G3648B
  template: src=sse_g3648_deploy.j2
            dest=/mnt/flash/startup-config
  when: device_info[inventory_hostname]["HwSku"] == "SSE-G3648B"
  become: yes

- name: reboot
  shell: sleep 2 && shutdown -r now "Reboot"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
