ansible_ssh_pass: ADMIN
ansible_ssh_user: ADMIN
fanout_mlnx_password: admin
fanout_mlnx_user: admin
fanout_network_password: '123456'
fanout_network_user: admin
fanout_shell_password: '123456'
fanout_shell_user: root
fanout_sonic_password: YourPaSsWoRd
fanout_sonic_user: admin
